### PR TITLE
Change Namespace from `nl.inl` to `org.allenai` in our fork of BlackLab

### PR DESCRIPTION
**Pull request by sbhaktha**
@dirkgr : As I was anticipating (we spoke about this a few weeks back), the authors of BlackLab contacted me. They've published their BlackLab. They don't want any confusion and want us to take down what we published under `nl.inl`. This changes the java namespaces so we can publish this version under `org.allenai`. Once I publish I'll change he dependency in IKE and take down the maven artifact.

### CODE REVIEW

**Comment by dirkgr** [comment]
Can we just use theirs? Why do we need to maintain our own?

Other than that, this looks good.

**Comment by sbhaktha** [comment]
you created this fork to put in your memory optimization fixes, right? Did they get merged?

**Comment by dirkgr** [comment]
I don’t think they got merged, but BlackLab has made their own changes, right? Maybe they optimized it themselves?

On June 7, 2016 at 12:56:32, Sumithra Bhakthavatsalam (notifications@github.com) wrote:

you created this fork to put in your memory optimization fixes, right? Did they get merged?

**Comment by dirkgr** [comment]
Actually, they did get merged: https://github.com/INL/BlackLab/pull/11

On June 7, 2016 at 12:59:42, Dirk Groeneveld (dirkg@allenai.org) wrote:

I don’t think they got merged, but BlackLab has made their own changes, right? Maybe they optimized it themselves?

On June 7, 2016 at 12:56:32, Sumithra Bhakthavatsalam (notifications@github.com) wrote:

you created this fork to put in your memory optimization fixes, right? Did they get merged?

**Comment by dirkgr** [comment]
So did all other changes that we submitted. You can actually find out if there is still unmergeded stuff by merging the tip of their master into the tip of ours, and then comparing.

On June 7, 2016 at 13:00:19, Dirk Groeneveld (dirkg@allenai.org) wrote:

Actually, they did get merged: https://github.com/INL/BlackLab/pull/11

On June 7, 2016 at 12:59:42, Dirk Groeneveld (dirkg@allenai.org) wrote:

I don’t think they got merged, but BlackLab has made their own changes, right? Maybe they optimized it themselves?

On June 7, 2016 at 12:56:32, Sumithra Bhakthavatsalam (notifications@github.com) wrote:

you created this fork to put in your memory optimization fixes, right? Did they get merged?

**Comment by sbhaktha** [comment]
That is good. But they've done more work on BlackLab since. We would need to retest IKE with their latest version. I'll try it out.

**Comment by sbhaktha** [comment]
And with the latest version of Blacklab, all of `ml` fails to compile because they've changed some APIs on us. The new version is also using a different version of Lucene, which is causing some errors.

**Comment by sbhaktha** [comment]
Merging this per our discussion.

**Pull request merged**
